### ISSUE TITLE
instance is not authenticated yet

### ISSUE THREAD

**Issue by devbuilder07** [ultramsg/whatsapp-php-sdk#12]

**Comment by kk8cc** [comment]
https://api.ultramsg.com/instance82354/messages/chat?token=09q71uch5nlum67m&to=k.w+96599109306@&body=%D8%B1%D8%B3%D8%A7%D9%84%D8%A9+%D8%AA%D8%AC%D8%B1%D9%8A%D8%A8%D9%8A%D8%A9+%D9%85%D9%86+UltraMsg.com&priority=10
