### ISSUE TITLE
I tried send a message

### ISSUE THREAD

**Issue by carlosdfb** [ultramsg/whatsapp-php-sdk#2]
show this error 
cURL Error #:SSL certificate problem: certificate has expired

the code is similar to page

<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.ultramsg.com/instance3857/messages/chat",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "token=f8yyphpu5xjj4nw8&to=+584241300079&body=La API de WhatsApp en UltraMsg.com funciona bien&priority=1&referenceId=",
  CURLOPT_HTTPHEADER => array(
    "content-type: application/x-www-form-urlencoded"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}

**Comment by ultramsg** [comment]
Hi  , if you are test in local server  
add :

 
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);

 
 
-----Original message-----
From: carlosdfb
Sent: Monday, March 14 2022, 9:56 pm
To: ultramsg/whatsapp-php-sdk
Cc: Subscribed
Subject: [ultramsg/whatsapp-php-sdk] I tried send a message (Issue #2)
 
 
show this error
cURL Error #:SSL certificate problem: certificate has expired

the code is similar to page

 "https://api.ultramsg.com/instance3857/messages/chat", CURLOPT_RETURNTRANSFER => true, CURLOPT_ENCODING => "", CURLOPT_MAXREDIRS => 10, CURLOPT_TIMEOUT => 30, CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1, CURLOPT_CUSTOMREQUEST => "POST", CURLOPT_POSTFIELDS => "token=f8yyphpu5xjj4nw8&to=+584241300079&body=La API de WhatsApp en UltraMsg.com funciona bien&priority=1&referenceId=", CURLOPT_HTTPHEADER => array( "content-type: application/x-www-form-urlencoded" ), )); $response = curl_exec($curl); $err = curl_error($curl); curl_close($curl); if ($err) { echo "cURL Error #:" . $err; } else { echo $response; }

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ultramsg** [comment]
Hi
Please add  :
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
