### ISSUE TITLE
Delivery Status Failure

### ISSUE THREAD

**Issue by hexxondiv** [ultramsg/whatsapp-php-sdk#5]
Hi,
Since 19/4/2022 19:28:47, I no longer receive Delivery and Read Status, both on Dashboard and on API calls.
Kindly rectify.
Thanks

**Comment by ultramsg** [comment]
If you want to activate ACK to know the status of messages you must activate this option :
"Webhook on ACK"
You will find it in the Instance settings.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/95187366/166128682-00a0245d-5d41-47d6-9aa7-bd066c72fcf3.png">

Or update it through the API
https://docs.ultramsg.com/api/post/instance/settings
