### ISSUE TITLE
Send Message in Proper Formatted Manner

### ISSUE THREAD

**Issue by khanmudassir124** [ultramsg/whatsapp-php-sdk#7]
This library is remarkably amazing, this solved my headache with low cost, but need guidance on How to send a msg in a proper formatted manner like with new line and indentation and how can I send link with my proper formatted message.
#highpriority

**Comment by ultramsg** [comment]
Hi ,khanmudassir124 
Thank you for using our service
You can talk to technical support and you will find this via the technical support icon on the site.

Regards
